app/src/main/java/se/medituner/app/MojoScreen.java
app/src/main/java/se/medituner/app/Popup.java
app/src/main/res/layout/popup.xml
app/src/main/res/values/strings.xml

* Added buttons to the popup window.
* Made a helper class for popups to optimise for possible future popups.
* Made both buttons dismiss the popup window.

Improved popup window.

---

app/src/main/res/drawable/arm_animation.xml
app/src/main/res/drawable/arm_animation_grinning.xml

Mojo animation

---

.idea/misc.xml
app/src/main/java/se/medituner/app/MojoScreen.java
app/src/main/res/values/strings.xml

* Added "Streak: " prefix
* Streak now resets on not taking medication.

Modified streak text

---

.idea/misc.xml
app/src/main/java/se/medituner/app/MojoScreen.java
app/src/main/res/layout/question_popup.xml
app/src/main/res/values/colors.xml

* Made the popup image toggle
* Tweaked popup background color

Tweaked popup

---

app/src/main/java/se/medituner/app/MojoScreen.java

Implemented streak persistence

streak persistence

---

app/src/main/java/se/medituner/app/MojoScreen.java
app/src/main/java/se/medituner/app/Schedule.java
app/src/main/java/se/medituner/app/Streak.java

* Reworked streaks
* Fixed several bugs

Reward streak

---

app/src/main/AndroidManifest.xml
app/src/main/java/se/medituner/app/Background.java
app/src/main/java/se/medituner/app/GetRequest.java
app/src/main/java/se/medituner/app/MojoScreen.java
app/src/main/java/se/medituner/app/game/GameScreen.java
app/src/main/java/se/medituner/app/game/GameSurfaceView.java
app/src/main/java/se/medituner/app/game/IScene.java
app/src/main/java/se/medituner/app/game/Quad.java
app/src/main/java/se/medituner/app/game/Scene.java
app/src/main/java/se/medituner/app/game/Shaders.java

* Refactored some of the Game code
* Moved most of the Game code to game package
* Added comments to most of the Game code.

Refactorings

---

app/src/main/java/se/medituner/app/game/GameScreen.java
app/src/main/java/se/medituner/app/game/GameSurfaceView.java
app/src/main/java/se/medituner/app/game/HighScore.java
app/src/main/java/se/medituner/app/game/Scene.java
app/src/main/java/se/medituner/app/game/Shaders.java
app/src/main/res/layout/game_view.xml
app/src/main/res/values/strings.xml

* Added reset on collision.
* Refactored and reworked HighScore.

Refactored HighScore.

---

app/src/main/res/layout/game_view.xml
app/src/main/res/values/strings.xml

* Changed 'HISCORE' text to 'HIGH SCORE'.

Sprint 3 Build 2

---

app/src/main/java/se/medituner/app/game/GameScreen.java
app/src/main/java/se/medituner/app/game/GameSurfaceView.java
app/src/main/java/se/medituner/app/game/HighScore.java
app/src/main/java/se/medituner/app/game/Scene.java
app/src/main/res/values/strings.xml
build.gradle

* Made tapping anywhere on the screen move Mojo.
* Fixed sleep re-launching point timer.
* Made hitboxes smaller.

Made several small fixes to the app

---

app/src/main/java/se/medituner/app/game/GameScreen.java
app/src/main/java/se/medituner/app/game/Obstacle.java
app/src/main/java/se/medituner/app/game/Scene.java

* Added game invulnerability
* Added background color change for the invulnerability

Game invulnerability

---

.idea/misc.xml
app/src/main/java/se/medituner/app/MojoScreen.java
app/src/main/java/se/medituner/app/game/GameScreen.java
app/src/main/java/se/medituner/app/game/Scene.java

* Starting a game with a non-0 streak will have different invulnerability period depending on the streak.
* The invulnerability time to streak is an asymptotic curve, meaning it will approach 30 seconds, but never quite reach it. At 1 week the invulnerability time gained per point of streak starts decreasing drastically.

Invulnerability resource

---

app/src/main/AndroidManifest.xml

Fix for issue #68 .
Enabled large heap size for the app.

Fixed app crash on popup appearing

---

app/src/main/res/values/strings.xml

translated "Pill" etc. to swedish ("medicinen") to prevent it from looking like a male name....

translated three static meds to swedish

---

.idea/misc.xml
app/src/main/java/se/medituner/app/IClock.java
app/src/main/java/se/medituner/app/MojoScreen.java
app/src/main/java/se/medituner/app/Schedule.java
app/src/main/java/se/medituner/app/SystemClock.java

Story 24 - _Show earlier medication_
- open the app shows all not taken meds from morning/lunch/evening for that day
- if there are meds left not taken at 5 AM the next morning the streak "nivå" will go down to 0

Three queues

---

app/src/main/java/se/medituner/app/MojoClothingList.java
app/src/main/java/se/medituner/app/MojoScreen.java

Refactored code

---

app/src/main/AndroidManifest.xml
app/src/main/java/se/medituner/app/MojoScreen.java
app/src/main/java/se/medituner/app/OptionsScreen.java
app/src/main/java/se/medituner/app/game/GameScreen.java
app/src/main/java/se/medituner/app/game/HighScore.java
app/src/main/java/se/medituner/app/game/Scene.java
app/src/main/res/layout/activity_mojo_screen.xml
app/src/main/res/layout/activity_options_screen.xml
app/src/main/res/menu/options_menu.xml
app/src/main/res/values/strings.xml

Includes #76 and #78 
* Added game background slowdown video

Option slowdown

---

app/src/main/AndroidManifest.xml
app/src/main/java/se/medituner/app/MojoScreen.java
app/src/main/java/se/medituner/app/OptionsScreen.java
app/src/main/java/se/medituner/app/game/GameScreen.java
app/src/main/java/se/medituner/app/game/HighScore.java
app/src/main/res/layout/activity_mojo_screen.xml
app/src/main/res/layout/activity_options_screen.xml
app/src/main/res/menu/options_menu.xml
app/src/main/res/values/strings.xml

* Fixed some options
* Refactored parts of MojoScreen
* Added reset sterak option

Option reset streak

---

app/src/main/java/se/medituner/app/MojoScreen.java
app/src/main/res/layout/activity_mojo_screen.xml

Got rid of glasses

---

app/src/main/java/se/medituner/app/Schedule.java
app/src/test/java/se/medituner/app/ScheduleUnitTests.java

* Added schedule day skipping test.

Added and improved upon Schedule tests

---

app/src/main/java/se/medituner/app/MojoScreen.java
app/src/main/res/layout/activity_mojo_screen.xml
app/src/main/res/values/strings.xml

* Added Mojo greeting.
* Added Mojo congratulation bubble.

Mojo congrats

---

.idea/misc.xml
app/src/main/AndroidManifest.xml

* Prevented options screen from going landscape mode.

Fixed options screen rotating

---

app/src/main/res/layout/activity_options_screen.xml

* Minor refactoring to settings screen layout.
* Fixed settings sizing on larger screens.

Rafactored settings
